-- Criar Base de Dados
CREATE DATABASE IF NOT EXISTS cifras_app
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE chordpro_db;

-- Tabela de Utilizadores
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela de Cifras
CREATE TABLE IF NOT EXISTS cifras (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  title VARCHAR(150) NOT NULL,
  artist VARCHAR(150),
  file_path TEXT NOT NULL,
  is_public BOOLEAN DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Tabela de Setlists
CREATE TABLE IF NOT EXISTS setlists (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  name VARCHAR(150) NOT NULL,
  is_public BOOLEAN DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Tabela dos Itens de cada Setlist
CREATE TABLE IF NOT EXISTS setlist_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  setlist_id INT NOT NULL,
  cifra_id INT NOT NULL,
  position INT DEFAULT 0,
  FOREIGN KEY (setlist_id) REFERENCES setlists(id) ON DELETE CASCADE,
  FOREIGN KEY (cifra_id) REFERENCES cifras(id) ON DELETE CASCADE
);
