# ----------------------------------------------------------------------------
# AMANDA - Waylon Jennings/Don Williams
# ----------------------------------------------------------------------------
{ns}
{t: AMANDA - Waylon Jennings/Don Williams}
{st: (McDill)}
{artist: Waylon Jennings; Don Williams}
{composer: McDill}


https://www.youtube.com/watch?v=R_WjVFhAgCo  (Capo 0) Waylon Jennings

https://www.youtube.com/watch?v=0_Vw6UrEKq4  (Capo 0) Don Williams

TIP:  The lyrics are slightly different between Waylon and Don.  This is Waylon's version.  

  
[INTRO:]     [A][,]     [A][,]     [A][,]     [A]


I've held it all inward, [D]God knows I've [A]tried.  
But it's an awful awakening, in a [E]country boy's [A]life.
To look in the mirror in [D]total sur[A]prise, 
At the hair on my shoulders and the [E]age in my [A]eyes.


Amanda, [D]light of my [A]life.   Fate should have made you, a [E]gentleman's [A]wife.  
Amanda, [D]light of my [A]life.   Fate should have made you, a [E]gentleman's [A]wife.


[A] [D]     [A][,]     [A]     [E]     [A]


It's a [A]measure of people, who [D]don't under[A]stand, 
The pleasures of life, in a [E]hillbilly [A]band.
I got my first guitar, when [D]I was [A]fourteen.  
Well I finally made forty, [E]still wearing [A]jeans.


Amanda, [D]light of my [A]life.   Fate should have made you, a [E]gentleman's [A]wife.  
Amanda, [D]light of my [A]life.   Fate should have made you, a [E]gentleman's [A]wife. 


[A] [D]     [A][,]     [A]     [E]     [A][;]       [A]     [D]     [A][,]     [A]     [E]     [A]






