# ----------------------------------------------------------------------------
# AMARILLO BY MORNING – George Strait 
# ----------------------------------------------------------------------------
{ns}
{define: F base-fret 1 frets x x 3 2 1 1} 
{define: F#m base-fret 1 frets x x x 2 2 2} 
{t: AMARILLO BY MORNING – George Strait}
{st: (Stafford/Fraser)}
{artist: George Strait}
{composer: Stafford; Fraser}
https://www.youtube.com/watch?v=IZBf16B5vhs  (Capo 2)


TIP:  There's a key change in which you'll be playing the (F#m) from the (D).  Two of your fingers are already on the 2nd fret so just collapse and play a barre.
 
 
[INTRO:]     [C]     [Em]       [F]    [G][,]     [C]     [Em]       [F]    [G7]
       

[C]Amarillo by [Em]mornin', [F]up from San An[C]tone.  
Everything that [Em]I got, is [F]just what I've got [G7]on.
When that [F]sun is high in that [G]Texas sky, I'll be [C]buckin' at the [Em]county [F]fair.
[C]Amarillo by [G]mornin', Amar[F]illo [G7]I'll  be [C]there.  [Em]       [F]    [G7]


[C]They took my saddle in [Em]Houston, broke my [F]leg in Santa [C]Fe.  
Lost my wife and a [Em]girlfriend, some[F]where along the [G7]way. 
I'll be [F]lookin' for eight when they [G]pull that gate, and I [C]hope that [Em]judge ain't [F]blind.
[C]Amarillo by [G]mornin', Amar[F]illo's [G7]on my [C]mind.  [Em]       [F]    [G7]


<key change>


[D]Amarillo by [F#m]Mornin', [G]up from San An[D]tone.  
Everything that [F#m]I got, is [G]just what I've got [A]on.
I ain't [G]got a dime but what I [A]got is mine.   I ain't [D]rich, but [F#m]Lord I'm [G]free.  
[D]Amarillo by [A]mornin', Amar[G]illo's [A7]where I'll [D]be.

[|][G][|][-][|][A7][|]     [D]Amarillo by [A]mornin', Amar[G]illo's [A7]where I'll [D]be.

[D] [F#m]          [G]     [A][;]       [D]     [F#m]          [G]     [A][;]       [D]     [F#m]          [G]     [A][;]     [|][D][|]


 

