# ----------------------------------------------------------------------------
# AMERICAN PIE - Don McLean  
# ----------------------------------------------------------------------------
{ns}
{t: AMERICAN PIE}
{t:  Don McLean }
{artist: Don McLean}
{composer: Don McLean}


https://www.youtube.com/watch?v=iX_TFkut1PM  (Capo 0)

TIP:  A chord in vertical brackets - |Am| - means strum just once at that position.}

TIP:  February 3rd, 1959.  (The day the music died.)  
 
           
A  [|]  l[G]ong[|]   [|]  l[D]ong[|]   [|][Em]time[|]   ago,  
[|][Am]I  [|]   can still remem  [|]b[C]er [|]   how that  [|] [Em]music[|],   used to make me [D]smile.
And  [|][G]I [|]   knew  [|][D]if [|]   I  [|][Em]had[|]   my chance, that  [|]  [Am]I   [|]   could make those  [|] pe[C]ople[|]   dance
And  [|] m[Em]aybe[|]   they'd be  [|] ha[C]ppy,[|]   for a  [|] w[D]hile.[|]     


But  [|] Fe[Em]bruary[|]   [|] [Am]made[|]   me shiver,  [|] [Em]with[|]   every paper  [|][Am]I'd [|]   deliver.
[|]B[C]ad[|]   news  [|][G]on[|]   the  [|][Am]door[|]   step, I  [|] co[C]uldn't[|]   take one more  [|] s[D]tep.[|]
I  [|] c[G]an't[|]   remember  [|][Em]if [|]   I  cried when I  [|] r[C]ead[|]   about his  [|] wid[D]owed[|]   bride.
[|]S[G]ome[|]   thing   [|] tou[D]ched[|]   me  [|][Em]deep[|]   inside, the  [|] d[C]ay,[|]   the  [|] m[D]usic,[|]   [|] d[G]ied.[|]    


So [G]bye [C]bye Miss A[G]merican [D]Pie.   Drove my [G]Chevy to the [C]levee but the [G]levee was [D]dry.
And them [G]good ole [C]boys were drinking [G]whiskey and [D]rye singin'  [|]  t[Em]his'll[|]   be the day that I  [|] d[A]ie.[|]  
[|]T[Em]his'll[|]   be the day that I [D]die. 


[G]Did you write the [Am]book of love and do [C]you have faith in [Am]God above, 
[Em]If the Bible [D]tells you so?
Now do [G]you believe in [D]rock and [Em]roll can [Am]music, save your [C]mortal soul and, 
[Em]Can you teach me [A7]how to dance [D]real slow?


Well I  [|] k[Em]now[|]   that you're in  [|] l[C]ove[|]   with him cause I  [|][Em]saw[|]   you dancin'  [|][C]in [|]   the gym.
[C]You both kicked off your [Am]shoes, man I [C]dig those rhythm and [D]blu-ues
I was a [G]lonely teenage broncin' [Em]buck, with a [Am]pink carnation and a [C]pickup truck.
But [G]I knew I was [Em]out of luck the [C]day, the [D]mu-sic [G]died. [C][-][G]     I started [D]singin'


[G]Bye [C]bye Miss A[G]merican [D]Pie.   Drove my [G]Chevy to the [C]levee but the [G]levee was [D]dry.
And them [G]good ole [C]boys were drinking [G]whiskey and [D]rye singin'  [|]  t[Em]his'll[|]   be the day that I  [|] [A]die.[|] 
[|][Em]This'll[|]   be the day that I [D]die. 


Now for [G]ten years we've been [Am]on   our own and [C]moss grows fat on a [Am]rolling stone but, 
[Em]That's not how it [D]used to be.  
When the [G]jester sang for the [D]king and [Em]queen in a [Am]coat, he borrowed [C]from James Dean and a [Em]voice, 
That [A]came [A7]from you and [D]me. 


Oh and  [|][Em]while[|]   the king was  [|] lo[C]oking[|]   dow-own the  [|] j[Em]ester[|]   stole his  [|] th[C]orny[|]   crown.
The [C]courtroom was ad[Am]journed, [C]no verdict was re[D]turned, 
And while [G]Lennon read a [Em]book on Marx, the [Am]quartet practiced [C]in the park, 
And [G]we sang dirges [Em]in   the dark the [C]day, the [D]mu-sic [G]died. [C][-][G]      We were [D]singin' 


[G]Bye [C]bye Miss A[G]merican [D]Pie.   Drove my [G]Chevy to the [C]levee but the [G]levee was [D]dry.
Them [G]good ole [C]boys were drinking [G]whiskey and [D]rye singin'  [|]  t[Em]his'll[|]   be the day that I  [|][A7]die[|].
[|]T[Em]his'll[|]   be the day that I [D]Die.  


[G]Helter skelter [Am]in    a summer swelter the [C]birds, flew off with a [Am]fallout shelter.  
[Em]Eight miles high and falling [D]faaaaaaaaaa-[G]ast it landed foul [Em]on   the grass,
The [Am]players tried for a [C]forward pass with the [Em]jester, on the [A]sidelines, in a [D]cast. [D]


Now the  [|][Em]half[|]   time air was,  [|] s[D]weet[|]   perfume while the  [|] se[Em]rgeants[|]   played a  [|] ma[D]rching[|]   tune.  
[C]We all got up to [Am]dance ohhhh but we, [C]never got the [D]chance.  
Cause the [G]players tried to [Em]take the field, the [Am]marching band re[C]fused to yield.  
[G]Do you recall what [Em]was revealed the [C]day, the [D]mu-sic [G]died? [C][-][G]      We started [D]singin' 


[G]Bye [C]bye Miss A[G]merican [D]Pie.   Drove my [G]Chevy to the [C]levee but the [G]levee was [D]dry.
And them [G]good ole [C]boys were drinking [G]whiskey and [D]rye singin'  [|] t[Em]his'll[|]   be the day that I  [|][A7]die,[|]   
[|]T[Em]his'll[|]   be the day that I [D]die.   


Ohhhh [G]and there we were all [Am]in one place, 
A [C]generation [Am]lost in space with [Em]no time left to [C]start a [D]gain.  
So come on, [G]Jack be nimble, [Em]Jack be quick, 
[Am]Jack Flash sat on a [C]candlestick cause, [Em]fire is the [A]devil's only [D]friend. 


Ohhhh  [|][Em]and[|]   as I watched him  [|][D]on[|]   the stage my  [|] h[Em]ands[|]   were clenched in  [|] fi[D]sts[|]   of rage, 
[C]No angel [G]born in [Am]Hell, could [C]break that Satan's [D]spell.
And as the [G]flames climbed [D]high in [Em]to   the night, to [Am]whom light the sacri[C]ficial rite 
I saw [G]Satan laughing [Em]with delight the [C]day, the [D]mu-sic [G]died. [C][-][G]      He was [D]singin'  


[G]Bye [C]bye Miss A[G]merican [D]Pie.   Drove my [G]Chevy to the [C]levee but the [G]levee was [D] dry.
And them [G]good ole [C]boys were drinking [G]whiskey and [D]rye singin'  [|] t[Em]his'll[|]   be the day that I  [|] d[A]ie.[|]     
[|]T[Em]his'll[|]   be the day that I [D]die. 


[|][G]I [|]   met a  [|][D]girl[|]   who  [|][Em]sang[|]   the blues, and  [|][Am]I [|]   asked her for some  [|] ha[C]ppy[|]   news,
But  [|][Em]she[|]   just smiled and  [|] tu[D]rned[|]   away. 
[|][G]I [|]   went  [|] d[D]own[|]   to the  [|] s[Em]acred[|]   store, where I'd  [|] h[Am]eard[|]   the [|] m[G]usic,[|]   [|] y[Am]ears[|]   before,
But the  [|][Em]man[|]   there, said the  [|] m[C]usic,[|]   wouldn't [Em]plaaa- [|][D]ay.[|]


And  [|] [Em]in [|]   the streets the  [|] ch[Am]ildren[|]   screamed, the  [|] l[Em]overs[|]   cried and the  [|][Am]poets[|]   dreamed.  
But  [|] n[C]ot [|]   a word was  [|] sp[Am]oken[|],   the  [|] ch[C]urch[|]   bells all were  [|] br[D]oken[|].
And the  [|] th[G]ree[|]   men  [|][D]I [|]   admire  [|][Em]most,[|]   the  [|] F[Am]ather[|]   Son and, the  [|]  H[D]oly[|]   Ghost,
[|] T[G]hey[|]   caught the  [|] l[D]ast[|]   train  [|][Em]for [|]   the coast, the  [|]d[C]ay,[|]   the  [|] m[D7]usic[|]    [|] d[G]ied.[|]     
[NC]And they were singin'


<slower>   [G]Bye [C]bye Miss A[G]merican [D]Pie.   Drove my [G]Chevy to the [C]levee but the [G]levee was [D]dry.
And them [G]good ole [C]boys were drinking [G]whiskey and [D]rye singin'  [|]  t[Em]his'll[|]   be the day that I  [|][A7]die.[|]  
[|]T[Em]his'll[|]   be the day that I [D]Die.   


They were [D7]singing [G]bye [C]bye Miss A[G]merican [D]Pie.   Drove my [G]Chevy to the [C]levee but the [G]levee was [D]dry.
Them [G]good ole [C]boys were drinking [G]whiskey and [D]rye singin' [C]this'll be the [D]day that I [|][G]die[|]. [-][|][C][|][-][|][G][|]
 


