# ----------------------------------------------------------------------------
# ANGEL OF THE MORNING – Juice Newton
# ----------------------------------------------------------------------------
{ns}
{t: ANGEL OF THE MORNING – Juice Newton}
{st: (Taylor)}
{artist: Juice Newton}
{composer: Taylor}


https://www.youtube.com/watch?v=HTzGMEfbnAw  (Capo 1)


[INTRO:]     [Em]       [C][,]     [D]     [Em][;]     [C]     [C][,]     [G][,]     [C][,]     [D]     [D]


[G]There'll be no strings to bind your [D]hands, not if my [C]love can't bind your [G]hearrrt. [C]     [D]     [C]
[G]There's no need to, take a [D]stand, for it was [C]I  who chose to [G]starrrt. [C]     [D]
[|][C][|][-][|][G][|][-][|][Am][|]     I see no [C]need to, take me [D]home.   [Am]I'm old e[C]nough to face the [D]dawn.


[G]Just call me [C]angel of the [D]morning [C]an[D]gel.   [G]Just touch my [C]cheek before you [D]leave me, [C]ba[D]by.
[G]Just call me [C]angel of the [D]morning [C]an[D]gel.   [C]Then slowly, turn away, from [G]me. [C]     [D]     [C]


[G]Maybe the sun's light will be [D]dim, and it won't [C]matter any [G]howwww. [C]     [D]     [C]
[G]If morning's echo says we [D]sinned, well it was [C]what I wanted [G]nowww. [C]     [D]
[|][C][|][-][|][G][|][-][|][Am][|]     And if we're [C]victims of the [D]night, [Am]I    won't be [C]blinded by the [D]liiiight.


[G]Just call me [C]angel of the [D]morning [C]an[D]gel.   [G]Just touch my [C]cheek before you [D]leave me, [C]ba[D]by. 
[G]Just call me [C]angel of the [D]morning [C]an[D]gel.   [C]Then slowly turn away. 


I won’t, beg you to stay, with [G]me.   [G][,]     [C][,]     [G]
Through the [C] tears.  Of the [G]day.  [G][,]     [C][,]     [G] 
Of the [C]years.    [(][pause][)]     [G]ba-ay-ay-[D]by.


[G]Just call me [C]angel of the [D]morning [C]an[D]gel.   [G]Just touch my [C]cheek before you [D]leave me, [C]ba[D]by.
[G]Just call me [C]angel of the [D]morning [C]an[D]gel.   [G]Just touch my [C]cheek before you [D] leave me, [C]dar[D]lin’.
[G]Just call me [C]angel of the [D]morning [C]an[D]gel.    
[G]Just touch my [C]cheek before you [D]leave me, [Cmaj7]dar - ar - [G]lin’. 

[G] [C]     [D]     [C][-][D][,]     [|][G][|]