# ----------------------------------------------------------------------------
# ANGIE - The Rolling Stones
# ----------------------------------------------------------------------------
{ns}
{define: E7 base-fret 1 frets 0 2 0 1 0 0} 
{define: F base-fret 1 frets x x 3 2 1 1} 
{t: ANGIE - The Rolling Stones}
{st: (Richards/Jagger)}
{artist: The Rolling Stones}
{composer: Keith Richards; Mick Jagger}

https://www.youtube.com/watch?v=K5_EBAzIPJM  (Capo 0)
 

[INTRO:]     [Am][,]     [E]     [E][-][E7][,]     [G]     [F][;]       [F]     [C][,]     [G]     [Am]
                                                                                                                                                            .
Angie,  [E]An [E7]gie,  [G]when will those clouds [F]all disappear-[C]er?  
[Am]Angie,  [E]An [E7]gie,  [G]where will it lead [F]us from here-[C]ere?
With no [G]loving in our souls, and no [Dm]money in our [Am]coats, 
[C]You can't [F]say we're satis[G]fied.
But [Am]Angie,  [E]An [E7]gie,  [G]you can't [F]say we never tri-[C]ed?


[Am]Angie, you're [E]beauti[E7]ful, yeah.  
[G]But ain't it time we [F]said goodby-[C]eye?
[Am]Angie, I still [E]love [E7]you, 
[G]Remember all those [F]nights we cri-[C]ied? 


All the [G]dreams we held so close, seemed to [Dm]all go up in [Am]smoke.  
[C]Let me [F]whisper in your [G]ear:  
"[Am]Angie,  [E]Angie,  [G]where will it [F]lead us, from here-[C]ere?"


[Am] [E]     [E7][,]     [G]     [F]     [Dm]        [C][;]       [Am]       [E]     [E7][,]     [G]     [F]     [Dm]        [C]


Ohhh [G]Angie don't you weep, all your [Dm]kisses still taste [Am]sweet.  
[C]I hate that [F]sadness in your [G]eyes. 
But [Am]Angie,  [E]An [E7]gie,  [G]ain't it [F]time we said goodby-[C]eye?


[Am] [E]     [E7][,]     [G]     [F]     [Dm]        [C]


With no [G]loving, in our souls, and no [Dm]money in our [Am]coats, 
[C]You can't [F]say were satis[G]fied.
But [Dm]Angie, I still love you [Am]baby.   [Dm]Everywhere I look, I see your [Am]eyes.
[Dm]There ain't a woman that comes [Am]close to you.   [C]Come on [F]baby dry your [G]eyes.


[Am]Angie,  [E]An [E7]gie,  [G]ain't it [F]good to be ali-[C]ive? 
 
[Am]Angie,  [E]An [E7]gie,  [G]they can't [F]say we never tri-[C]ied. 



