# ----------------------------------------------------------------------------
# ANKLE DEEP - Tom Petty
# ----------------------------------------------------------------------------
{ns}
{define: F base-fret 1 frets x x 3 2 1 1} 
{t: ANKLE DEEP}
{t:  Tom Petty }
{artist: Tom Petty}
{composer: Tom Petty}


https://www.youtube.com/watch?v=Ue9UYWSX9hw  (Capo 0)
 

[INTRO:]     [C][,]     [C][,]     [C][,]     [C]


Well they raised, that [G]horse, to be a [C]jumper.  He was [F]owned by a Midwest bible [C]thumper.
His [F]preacher was a Louisiana [Am]drummer.  Took all [G]winter, to get through the [C]summer.  


The fieldhand, hit the [G]switch, and [C]stumbled.  Out[F]side, the big engine roared and [C]rumbled. 
The [F]sto, len horse, spooked, and [Am]tumbled.  She didn't [G]speak, for a week, just kinda [C]mumbled.
 

[Am]Ankle deep, in [Em]love.   [Am]Ankle deep, in [G]love.


[C] [G]     [C][,]     [F]    [C][,]     [G]     [C][;]       [C][,]     [C][,]     [C][,]     [C][;]       [C][,]     [C][,]     [C][,]     [C]


[Am]Ankle deep, in [Em]love.   [Am]Ankle deep, in [G]love. 


He was [C]caught up, in a [G]lie, he half be[C]lieved.  Found her [F]hiding high in the family [C]tree.
Washed his [F]hands, and put her cross his [Am]knee.  She said "[G]Daddy, you been a mother to [C]me."


[Am]Ankle deep, in [Em]love.   [Am]Ankle deep, in [G]love.
[Am]Ankle deep, in [Em]love.   [Am]Ankle deep, in [G]love.


[C][,]     [C][,]     [C][,]     [C][;]       [C][,]     [C][,]     [C][,]     [C] 



