# ----------------------------------------------------------------------------
# ANNIE’S SONG – John Denver
# ----------------------------------------------------------------------------
{ns}
{t: ANNIE’S SONG}
{t: John Denver}
{artist: John Denver}
{composer: John Denver}


https://www.youtube.com/watch?v=RNOTF-znQyw   (Capo 0)

                                                                                                                                                                        .          
[INTRO:]     [D]


You fill up me [G]sen[A]ses, [Em]like a night in a [D]forest.
Like the [A]mountains in [G]spring [A]time, [Em]like a [G]walk in the [A]rain.  
Like a storm in the [G]des[A]ert, [Em]like a [G]sleepy blue [D]ocean.
You [A]fill up my [G]sen[A]ses, [Em]come [A]fill me a[D]gain.


Come let me [G]love [A]you.   [Em]Let me [G]give my life [D]to you.
Let me [A]drown in your [G]laugh[A]ter, [Em]let  me [G]die in your [A]arms.
Let me lay down be[G]side [A]you, [Em]let  me [G]always be [D]with you.
[A]Come let me [G]love [A]you, [Em]come [A]love me a[D]gain.


[D] [G]     [A]     [Em][,]       [G]     [D]     [A]     [Em][,]       [A]     [G]     [A]     [Em][,]       [G]     [A][,]       [A]     [G]     [A]     [Em]
 

Let me [G]give my life [D]to you.   
[A]Come let me [G]love [A]you, [Em]come [A]love me a[D]gain. 


You fill up me [G]sen[A]ses, [Em]like a night in a [D]forest. 
Like the [A]mountains in [G]spring [A]time, [Em]like a [G]walk in the [A]rain.  
Like a storm in the [G]des[A]ert,  <gently>   [Em]like a [G]sleepy blue [D]ocean. 
You [A]fill up my [G]sen[A]ses, [Em]come [A]fill me a[D]gain.

 

