# ----------------------------------------------------------------------------
# APRIL, COME SHE WILL - Simon & Garfunkel
# ----------------------------------------------------------------------------
{ns}
{define: Fmaj7 base-fret 1 frets x x 3 2 1 0} 
{t: APRIL, COME SHE WILL - Simon & Garfunkel}
{st: (Simon)}
{artist: Simon and Garfunkel}
{composer: Paul Simon}


https://www.youtube.com/watch?v=HTzGfekWI50  (Capo 3)

TIP:  The first word in each verse is held for two counts.  That's what the ... means.

TIP:  (Fmaj7) isn't played too often.  Play it like you're going to play a regular (F) but don't barre the bottom string.  If it's too difficult then just play an (F) instead.

      
[INTRO:]     [G]     [C][-][G][,]     [G]     [C][;]       [G]     [C][-][G]     [D]     [G][,]     [G]     [C][-][G][,]     [G]     [C][-][G]


[G]A... [C]a- [G]pril,  [C]come she [G]will. [C][-][G]  
[Am]When streams are [Em]ripe and [Fmaj7]swelled with [Em]rain.  
[C]Ma- [D]ay she will [G]sta- [Em]ay.  
[Am]Resting [Em]in my [Am]arms a [Em]gain. [G]     [C][-][G][,]     [G]     [C][-][G] 


[G]Ju... [C]un- [G]une,  [C]she´ll change her [G]tune. [G]     [C][-][G][,]     [G]     [C][-][G]
[Am]In  restless [Em]walks she´ll [Fmaj7]prowl the [Em]night.  
[C]July-[D]y, she will [G]fly- [Em]y.
[Am]And give no [Em]warning [Am]to   her [Em]flight. [G]     [C][-][G][,]     [G]     [C][-][G] 


[G]Au... [C]au- [G]gust,  [C]die she [G]must. [C][-][G]  
[Am]The autumn [Em]winds blow [Fmaj7]chilly and [Em]cold.  
[C]Septem[D]ber I´ll re[G]mem[Em]ber.  
[Am]A   love once [Em]new has [D]now, grown [G]old. 


[G] [C][-][G][,]     [G]     [C][;]       [G]     [C][-][G]     [D]     [G]
 



