# ----------------------------------------------------------------------------
# ARE THE GOOD TIMES REALLY OVER FOR GOOD – Merle Haggard
# ----------------------------------------------------------------------------
{ns}
{define: F base-fret 1 frets x x 3 2 1 1} 
{t: ARE THE GOOD TIMES REALLY OVER FOR GOOD}
{t:  Merle Haggard}
{artist: Merle Haggard}
{composer: Merle Haggard}


https://www.youtube.com/watch?v=sxLtXJzo3Ew  (Capo 0)
     

[INTRO] [(][slowly][)][:]     [C][,]   [C][;]     [C][,]   [C]

I wish a buck was still silver.   It was back, when the country was [F]strong.
Back before [G]Elvis, and before, the Vietnam war, came a[C]long.
Before The Beatles and 'Yesterday'.   When a man could still work, and still [F]would.
Is the best of the free life be[G]hind us now?   And are the good times really over for [C]good?


And are we rolling down hill like a snowball headed for [F]hell?  
With [G]no kind of chance for the flag or the liberty [C]bell.
I wish a Ford and a Chevy, would still last ten years like they [F]should.
Is the best of the free life be[G]hind us now?   Are the good times really over for [C]good? 


I wish [C]coke was still cola, and a joint, was a bad place to [F]be.
And it was back before Nixon, [G]lied to us, all on T [C]V. 
Before microwave ovens, when a girl, could still cook, and still [F]would.
Is the best of the free life be[G]hind us now?   Are the good times really over for [C]good? 


Are we rolling down hill like a snowball headed for [F]hell?  
With [G]no kind of chance for the flag, or the liberty [C]bell.
I wish a Ford and a Chevy, would still last ten years like they [F]should.
Is the best of the free life be[G]hind us now?   Are the good times really over for [C]good? 


Stop rolling down hill like a snowball headed for [F]hell.  
Stand [G]up for the flag and let's all ring the liberty [C]bell. 
Let's make a Ford and a Chevy, that’ll still last ten years like they [F]should.
Cuz the best of the free life is [G]still yet to come, and the good times ain't over for [C]good.



